#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGError
@end

@interface SWGError : SWGObject

/* Indicates whether the request was or was not successful [optional]
 */
@property(nonatomic) NSNumber* success;

@property(nonatomic) NSDate* currentServerTime;

@property(nonatomic) NSString* message;

@end
