#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGIssueStatus
@end

@interface SWGIssueStatus : SWGObject

/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;
/* The type of Issue this log is associated to. [optional]
 */
@property(nonatomic) NSString* type;
/* The status of the issue. [optional]
 */
@property(nonatomic) NSString* status;
/* Resolution type. [optional]
 */
@property(nonatomic) NSString* resolution;
/* Scheduled date/time. [optional]
 */
@property(nonatomic) NSString* scheduledTime;
/* Text describing the issue status/log event. [optional]
 */
@property(nonatomic) NSString* ticketSummaryText;
/* Text describing the issue status/log event. [optional]
 */
@property(nonatomic) NSString* historySummaryText;

@end
