#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGIssue
@end

@interface SWGIssue : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* Reference number. [optional]
 */
@property(nonatomic) NSString* referenceNum;
/* The primary key of the related *Merchant*. 
 */
@property(nonatomic) NSString* membersId;

@property(nonatomic) NSString* membersName;

@property(nonatomic) NSString* membersEmail;
/* The primary key of the related *MerchantLocation*. 
 */
@property(nonatomic) NSString* membersLocationsId;

@property(nonatomic) NSString* membersLocationsName;
/* The primary key of the related *MerchantUser*. 
 */
@property(nonatomic) NSString* membersUsersId;

@property(nonatomic) NSString* membersUsersName;

@property(nonatomic) NSString* membersUsersEmail;
/* Type. [optional]
 */
@property(nonatomic) NSString* type;
/* Category. [optional]
 */
@property(nonatomic) NSString* category;
/* Details. [optional]
 */
@property(nonatomic) NSString* details;
/* Status. [optional]
 */
@property(nonatomic) NSString* status;
/* Job type. [optional]
 */
@property(nonatomic) NSString* job;
/* Resolution type. [optional]
 */
@property(nonatomic) NSString* resolution;
/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;
/* Date last updated. [optional]
 */
@property(nonatomic) NSDate* updated;
/* Actual technician travel time. [optional]
 */
@property(nonatomic) NSDate* enrouteTime;
/* Date/time scheduled. [optional]
 */
@property(nonatomic) NSDate* scheduledTime;
/* Technician arrival time. [optional]
 */
@property(nonatomic) NSDate* arrivalTime;
/* Technician departure time. [optional]
 */
@property(nonatomic) NSDate* departureTime;

@end
