#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGIssueLog
@end

@interface SWGIssueLog : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* The primary key of the related *Issue*. 
 */
@property(nonatomic) NSString* issuesId;
/* Differences. [optional]
 */
@property(nonatomic) NSString* diffLog;
/* Notes. [optional]
 */
@property(nonatomic) NSString* notes;
/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;

@end
