#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGBaseResponse.h"
#import "SWGMemberUser.h"


@protocol SWGMemberUserResponse
@end

@interface SWGMemberUserResponse : SWGBaseResponse

/* Indicates success of the operation. [optional]
 */
@property(nonatomic) NSNumber* success;

@property(nonatomic) NSDate* currentServerTime;
/* Total records available. [optional]
 */
@property(nonatomic) NSNumber* totalCount;
/* Total records retrieved. [optional]
 */
@property(nonatomic) NSNumber* returned;
/* Total pages available. [optional]
 */
@property(nonatomic) NSNumber* pages;

@property(nonatomic) NSString* message;

@property(nonatomic) NSArray<SWGMemberUser>* results;

@end
