#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMember.h"
#import "SWGMemberLocation.h"
#import "SWGMemberUser.h"


@protocol SWGMemberCreateRequest
@end

@interface SWGMemberCreateRequest : SWGObject


@property(nonatomic) SWGMember* members;

@property(nonatomic) SWGMemberUser* membersUsers;

@property(nonatomic) SWGMemberLocation* membersLocations;

@end
