#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGMember.h"
#import "SWGMemberLocation.h"
#import "SWGMemberUser.h"


@protocol SWGMemberTuple
@end

@interface SWGMemberTuple : SWGObject


@property(nonatomic) SWGMember* member;

@property(nonatomic) SWGMemberUser* memberUser;

@property(nonatomic) SWGMemberLocation* memberLocation;

@end
