#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMemberLocation
@end

@interface SWGMemberLocation : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* The primary key of the related *Merchant*. [optional]
 */
@property(nonatomic) NSString* membersId;
/* Street address. 
 */
@property(nonatomic) NSString* street1;
/* Street address continued. [optional]
 */
@property(nonatomic) NSString* street2;
/* City. 
 */
@property(nonatomic) NSString* city;
/* State Identifier (2 char code). 
 */
@property(nonatomic) NSString* state;
/* Postal Code. 
 */
@property(nonatomic) NSString* zipcode;
/* Latitude. [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* Longitude. [optional]
 */
@property(nonatomic) NSNumber* longitude;
/* Phone number. [optional]
 */
@property(nonatomic) NSString* phone;
/* Informal reference, an alias. [optional]
 */
@property(nonatomic) NSString* siteName;

@end
