#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMember
@end

@interface SWGMember : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* Business name. 
 */
@property(nonatomic) NSString* name;
/* Business legal name. [optional]
 */
@property(nonatomic) NSString* nameLegal;
/* Street address. [optional]
 */
@property(nonatomic) NSString* street1;
/* Street address continued. [optional]
 */
@property(nonatomic) NSString* street2;
/* City. [optional]
 */
@property(nonatomic) NSString* city;
/* State Identifier (2 char code). [optional]
 */
@property(nonatomic) NSString* state;
/* Postal Code. 
 */
@property(nonatomic) NSString* zipcode;
/* Email address. 
 */
@property(nonatomic) NSString* email;
/* Phone number. [optional]
 */
@property(nonatomic) NSString* phone;
/* Industry. [optional]
 */
@property(nonatomic) NSString* industry;
/* Status. [optional]
 */
@property(nonatomic) NSString* status;
/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;

@end
