#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGMemberUser
@end

@interface SWGMemberUser : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* The primary key of the related *Merchant*. [optional]
 */
@property(nonatomic) NSString* membersId;
/* The primary key of the related *MerchantLocation*. [optional]
 */
@property(nonatomic) NSString* membersLocationsId;
/* First name. 
 */
@property(nonatomic) NSString* firstName;
/* Last name. 
 */
@property(nonatomic) NSString* lastName;
/* Concatenation of first and last name. [optional]
 */
@property(nonatomic) NSString* fullName;
/* Email address. 
 */
@property(nonatomic) NSString* email;
/* SMS capable phone number. [optional]
 */
@property(nonatomic) NSString* smsNumber;
/* Language. [optional]
 */
@property(nonatomic) NSString* lang;
/* Status. [optional]
 */
@property(nonatomic) NSString* status;

@end
