#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProviderTeam
@end

@interface SWGProviderTeam : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* Name. [optional]
 */
@property(nonatomic) NSString* name;
/* Hashtag nickname for group mentions in chat. [optional]
 */
@property(nonatomic) NSString* nickname;
/* Description. [optional]
 */
@property(nonatomic) NSString* _description;
/* Email address. [optional]
 */
@property(nonatomic) NSString* email;
/* Primary contact phone number. [optional]
 */
@property(nonatomic) NSString* phone;
/* URL to an avatar. [optional]
 */
@property(nonatomic) NSString* avatar;
/* Automatically routes related merchant issues to this ProviderTeam. [optional]
 */
@property(nonatomic) NSNumber* autoAssignRoute;
/* Automatically assigns this ProviderTeam as the sponsor for related merchants. [optional]
 */
@property(nonatomic) NSNumber* autoAssignSponsor;
/* Status. [optional]
 */
@property(nonatomic) NSString* status;
/* Type / Category. [optional]
 */
@property(nonatomic) NSString* type;
/* Exclusive within it's type / category. [optional]
 */
@property(nonatomic) NSNumber* exclusive;
/* Published to the Connect App. [optional]
 */
@property(nonatomic) NSNumber* published;
/* Name, as publushed in the Connect App. [optional]
 */
@property(nonatomic) NSString* publishedName;
/* Enable private label branding. [optional]
 */
@property(nonatomic) NSNumber* privateLabel;
/* Private label brand color, used if private_label is true. [optional]
 */
@property(nonatomic) NSString* brandColor1;
/* Private label logo, used if private_label is true. [optional]
 */
@property(nonatomic) NSString* brandLogo1x;
/* Private label logo (x2), used if private_label is true. [optional]
 */
@property(nonatomic) NSString* brandLogo2x;
/* Private label logo (x3), used if private_label is true. [optional]
 */
@property(nonatomic) NSString* brandLogo3x;
/* Primary support email address. [optional]
 */
@property(nonatomic) NSString* supportEmail;
/* Primary support phone number. [optional]
 */
@property(nonatomic) NSString* supportPhone;
/* Primary support website. [optional]
 */
@property(nonatomic) NSString* supportUrl;
/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;
/* Date last updated. [optional]
 */
@property(nonatomic) NSDate* updated;

@end
