#import <Foundation/Foundation.h>
#import "SWGProviderResponse.h"
#import "SWGError.h"
#import "SWGMemberResponse.h"
#import "SWGProviderTeamResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGProvidersApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGProvidersApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGProvidersApi*) sharedAPI;
///
///
/// Returns your Provider
/// Returns your *Provider* record
///
/// 
///
/// @return SWGProviderResponse*
-(NSNumber*) getProviderWithCompletionHandler: 
    (void (^)(SWGProviderResponse* output, NSError* error)) handler;


///
///
/// Returns Merchants
/// Returns collection of related *Merchant* records
///
/// 
///
/// @return SWGMemberResponse*
-(NSNumber*) getProviderMembersWithCompletionHandler: 
    (void (^)(SWGMemberResponse* output, NSError* error)) handler;


///
///
/// Returns a ProviderTeam
/// Returns a *ProviderTeam* record
///
/// @param providerTeamId The primary key of the ProviderTeam
/// 
///
/// @return SWGProviderTeamResponse*
-(NSNumber*) getProviderTeamWithProviderTeamId: (NSString*) providerTeamId
    completionHandler: (void (^)(SWGProviderTeamResponse* output, NSError* error)) handler;


///
///
/// Returns your ProviderTeams
/// Returns a collection of *ProviderTeam* records
///
/// 
///
/// @return SWGProviderTeamResponse*
-(NSNumber*) getProviderTeamsWithCompletionHandler: 
    (void (^)(SWGProviderTeamResponse* output, NSError* error)) handler;



@end
