#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGProvider
@end

@interface SWGProvider : SWGObject

/* Primary key. [optional]
 */
@property(nonatomic) NSString* _id;
/* Business name. [optional]
 */
@property(nonatomic) NSString* name;
/* Business legal name. [optional]
 */
@property(nonatomic) NSString* nameLegal;
/* Hashtag nickname for group mentions in chat. [optional]
 */
@property(nonatomic) NSString* nickname;
/* The communication channel id. [optional]
 */
@property(nonatomic) NSString* commId;
/* Description. [optional]
 */
@property(nonatomic) NSString* _description;
/* Street address. [optional]
 */
@property(nonatomic) NSString* street1;
/* Street address continued. [optional]
 */
@property(nonatomic) NSString* street2;
/* City. [optional]
 */
@property(nonatomic) NSString* city;
/* State Identifier (2 char code). [optional]
 */
@property(nonatomic) NSString* state;
/* Postal Code. [optional]
 */
@property(nonatomic) NSString* zipcode;
/* Business location latitude. [optional]
 */
@property(nonatomic) NSNumber* latitude;
/* Business location longitude. [optional]
 */
@property(nonatomic) NSNumber* longitude;
/* Default ProviderTeam's id. [optional]
 */
@property(nonatomic) NSString* defaultPartnersTeamsId;
/* Email address. [optional]
 */
@property(nonatomic) NSString* email;
/* Primary contact phone number. [optional]
 */
@property(nonatomic) NSString* phone;
/* Business website/URL. [optional]
 */
@property(nonatomic) NSString* website;
/* URL to an avatar. [optional]
 */
@property(nonatomic) NSString* avatar;
/* Date created. [optional]
 */
@property(nonatomic) NSDate* created;
/* Date last updated. [optional]
 */
@property(nonatomic) NSDate* updated;

@end
